listener 1883
allow_anonymous false
auth_plugin /mosquitto/auth/libmosquitto_jwt_auth.so
auth_opt_jwt_alg HS256
auth_opt_jwt_sec_env JWT_SIGNING_SECRET_BASE64
auth_opt_jwt_validate_exp true
auth_opt_jwt_validate_sub_match_username true
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information